### ISSUE TITLE
Juego de alfabeto en inglés

### ISSUE THREAD

**Issue by eduardokdna** [eduardokdna/alphabet#1]
[alphabet.zip](https://github.com/eduardokdna/alphabet/files/3447583/alphabet.zip)

No soy programador, cree este juego con un codigo que encontré y lo adapté a lo que necesito. El juego consiste en dar click en el botón que hace sonar el sonido de la letra y el usuario da click en la letra correspondiente si es correcto aparece una ventana con la ilustración y ejemplo en inglés, al dar click en otra debería salir un alert con un aviso de error pero no funciona.

**Comment by jocelo** [comment]
Hola.... creo que te puedo ayudar, asigname el issue.

**Comment by jocelo** [comment]
Hola @eduardokdna  ,

Cree el Pull Request #2  para solucionar este issue. Saludos!

**Comment by eduardokdna** [comment]
Hermano excelente muchas gracias funciona perfecto.

**Comment by jocelo** [comment]
Perfecto! Saludos!
